CREATE TABLE IF NOT EXISTS genres (
    genreID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    genreName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
    bookID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    bookName VARCHAR(255) NOT NULL,
    description TEXT,
    numberOfCopies INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS authors (
    authorID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    authorName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS publishers (
    publisherID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    publisherName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS book_genre (
    bookID INTEGER NOT NULL,
    genreID INTEGER NOT NULL,
    PRIMARY KEY (bookID, genreID),
    FOREIGN KEY (bookID) REFERENCES books(bookID) ON DELETE CASCADE,
    FOREIGN KEY (genreID) REFERENCES genres(genreID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_author (
    bookID INTEGER NOT NULL,
    authorID INTEGER NOT NULL,
    PRIMARY KEY (bookID, authorID),
    FOREIGN KEY (bookID) REFERENCES books(bookID) ON DELETE CASCADE,
    FOREIGN KEY (authorID) REFERENCES authors(authorID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_publisher (
    bookID INTEGER NOT NULL,
    publisherID INTEGER NOT NULL,
    year INTEGER NOT NULL,
    PRIMARY KEY (bookID, publisherID),
    FOREIGN KEY (bookID) REFERENCES books(bookID) ON DELETE CASCADE,
    FOREIGN KEY (publisherID) REFERENCES publishers(publisherID) ON DELETE CASCADE
);